blank_issues_enabled: false
contact_links:
  - name: ğŸ’ Support
    url: https://github.com/deepalgae/astro-now
    about: 'This issue tracker is not for support questions. Join us on Discord for assistance!'
  - name: ğŸ“˜ Documentation
    url: https://github.com/deepalgae/astro-now
    about: File an issue or make an improvement to the docs website.
  - name: ğŸ’¡ Ideas for New Features, Improvements and RFCs
    url: https://github.com/deepalgae/astro-now
    about: Propose and discuss future improvements to Astro
  - name: ğŸ‘¾ Chat
    url: https://github.com/deepalgae/astro-now
    about: Our Discord server is active, come join us!
